from dataclasses import dataclass
from typing import Any, Dict


@dataclass
class Event:
    pass


@dataclass
class MarketEvent(Event):
    """
    Event generated by Data Feed when new market data arrives.
    """
    symbol: str
    data_type: str  # e.g., 'tick', 'orderbook', 'kline'
    data: Dict[str, Any]


@dataclass
class SignalEvent(Event):
    """
    Event generated by a Strategy when a trading condition is met.
    """
    strategy_id: str
    symbol: str
    side: str  # 'buy' or 'sell'
    order_type: str # 'market', 'limit', etc.
    quantity: float
    price: float = None


@dataclass
class OrderEvent(Event):
    """
    Event handled by the Execution Layer to place an order.
    """
    symbol: str
    side: str
    order_type: str
    quantity: float
    price: float = None


@dataclass
class FillEvent(Event):
    """
    Event generated by the Execution Layer or Exchange Simulator when an order is filled.
    """
    symbol: str
    side: str
    quantity: float
    price: float
    fee: float
