"""initial_schema

Revision ID: ffbe0c5bd09c
Revises: 
Create Date: 2026-05-30 12:17:53.887436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbe0c5bd09c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_logs', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trade_logs', 'backtest_runs', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade_logs', type_='foreignkey')
    op.drop_column('trade_logs', 'run_id')
    # ### end Alembic commands ###
